# Application properties for Spring Boot gRPC application
spring.application.name=springboot-grpc

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/posts_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging configuration
logging.level.io.grpc=ERROR
logging.level.io.netty=ERROR
